### ISSUE TITLE
react warning

### ISSUE THREAD

**Issue by javascala** [hufeng/plume2#19]
大师写app的时候发现个小问题， React.PropTypes is no longer supported and will be removed completely in React 16
store-provider.tsx 
`static childContextTypes = {
        `_plume$Store:` React.PropTypes.object
      };`

**Comment by hufeng** [comment]
好的 我来研究下！估计要换新api了

**Comment by hufeng** [comment]
现在propstype单独分拆了 不从React里面调用

**Comment by hufeng** [comment]
开始迁移+1

**Comment by hufeng** [comment]
migrate https://github.com/hufeng/plume2/commit/6604a391f2b87b43e42a2bbb2f50f60c9c6d87d5

等待下个版本更新
