### ISSUE TITLE
是不是要open，bigQuery在计算DQL和QL的计算详情log

### ISSUE THREAD

**Issue by hufeng** [hufeng/plume2#4]
代码中已经添加了日志的跟踪，目前还没有放出来。
怎么在日志的多和需要之间平衡。

**Comment by hufeng** [comment]
@angrycans 豹哥 这里面要要开放bigQuery的日志跟踪，开放出来就感觉log有点多，不开放，怎么比较简单的开发日志

**Comment by angrycans** [comment]
在storeprovide 里面在价格debug 参数了 DQLDebug QLdebug

**Comment by hufeng** [comment]
@angrycans ok

**Comment by hufeng** [comment]
跟着默认debug走，如果开放太多的配置项，看着挺乱。
