### ISSUE TITLE
relax的inject的注入方式

### ISSUE THREAD

**Issue by hufeng** [hufeng/plume2#7]
目前Relax的容器组件给子组件的注入方式是通过约定实现，
1. 默认从props注入
2. 默认是store的state
3. 默认是store的method
4. 是QL

这些注入的方式通过约定在开发阶段非常灵活，但是给后期的代码维护带来了二义性，我们需要深入了解
代码才能知道具体的注入方式，例如
```js
@Relax
class ProductItem extends React.Component {
   static defaultProps = {
     index: 0, //props
     name: '',  //store' state
     onAddCart: noop //store's method
   };
}
```

但是后期再维护的时候，很难一眼看出index，name的注入方式，
另外这样的灵活也是有代价，比如，props透传了name，恰好store里面也是有name，惨了
props就被默认覆盖了，代码结果的不可预测性。

另外，由于store里聚合actor的state是immutable数据结构，如果想获取更深层次的数据，通过该方式无法实现了。

so针对以上这些情况，还是需要去固化我们的注入方式，一目了然，清晰简单

比如，只默认是props注入，

我们设计一个inject的模块，
如果是从store的state注入化，我们可以这样，
cursor(string | string[], any) //第一个参数是cursor的path路径，第二个参数是默认值
name: inject.cursor('name', '') 
而且这样还解决了深层嵌套的数据获取问题，比如store的state数据是
```js
fromJS({
  product: {
    id: 1,
    goods: {
      id: 1,
      name: 'plume2'
    }
  }
})
```
如果想去注入id进来，就是简单的
```js
id: inject.cursor(['product', 'goods', 'id'], 0) //ok
```

相注入store的method，
```js
onAddCart: inject.method('addCart') //自带默认值为noop
```

因此基于这个规范 我们就可以很清晰的知道数据的来源，
```js
static defaultProps = {
   index: 0,  //默认从props
   onDelete: noop, //默认从props


   product: inject.cursor('product', fromJS({}))  //store's state
   skuId: inject.cursor(['product', 'goods', 'id'], 0) //store's state
   onCartAdd: inject.method('cartAdd'),
}
```

**Comment by hufeng** [comment]
inject.cursor => 是不是容易和immutable的cursor弄混淆

或许inject.path() 比较好吧。

**Comment by hufeng** [comment]
扩展出storePath, storeMethod

**Comment by hufeng** [comment]
我们需要在易用性和可维护性之间去平衡很多的东西，
最后和豹哥讨论，可能这样比较好，

1. 约定大约配置是对的，问题是约定是不是能做一致性的约定，保证约定无二义性
2. 尽量不要入侵到react的默认的方法或者属性，这样相当于走了两套约定 容易混乱


现在的方案这样：我们扩出来一个单独的属性声明relaxProps,这么里面明确的就是和store进行数据的关联,for example

```js
@Relax
class HelloContainer extends React.Component<any, any> {
  //还是react的defaultProps没有任何的魔法
  static defaultProps = {text: 'hello world'};
  
 //需要注入的数据
 static relaxProps = {
    loadingStatus: 'loading', //会取store.state().get('loading')
    productName: ['product', 'name'], //回去取store.state().getIn(['product', 'name']),
    loadingQL,
    loadingDQL,
   loadingEnd: noop,  //注入store.loadingEnd()
 };
 
  render() {
    const {text} = this.props
    const {loadingStatus, productName, loadingQL, loadingDQL, loadingEnd} = this.props.relaxProps
    return (....);
  }
}
```

**Comment by angrycans** [comment]
👍
