### ISSUE TITLE
怎么在todo 的index.tsx 里面拿 store ？

### ISSUE THREAD

**Issue by angrycans** [hufeng/plume2#8]
this.store 语法通过不了？
this.props.store 也不对

如果这儿不支持@relax 在typescript 拿不到store吧 。除非修改react.component的d.ts
@StoreProvider(AppStore, { debug: __DEV__ })
//@Relax
export default class Login extends React.Component<any, any>
{

  render() {
    console.log("this.store",this.store);

**Comment by hufeng** [comment]
明白这个问题，relax不会透传store，只会去计算组件声明的属性，计算值作为props透传给组件

@StoreProvider的顶层组件里面想去取store，是可以的，直接通过this.store就可以拿到

@StoreProvider@Relax 这样一被relax隔断， 就不能通过this.store取到

**Comment by hufeng** [comment]
这块的api涉及到几个问题，还需要再思考下，

**Comment by hufeng** [comment]
@StoreProvider(AppStore)
class HelloApp extends React.Component<any, any> {
    store: AppStore;
}

**Comment by angrycans** [comment]
let {loading} = this.store; 继续报语法错误时，咋办

**Comment by angrycans** [comment]
难道是去appstore 里面增加个[propName: string]: any; 定义

**Comment by hufeng** [comment]
这地方数据可以从state里面拿，
这里的this.state = store.state().toObject()
